wandb_version: 1

wandb:
  desc: null
  value:
    entity: "halilteam"
    project: projectname
files:
  desc: null
  value:
    image_path: images
    annotation_file: databases/MIDOG++.sqlite
data:
  desc: null
  value:
    patch_size: 512
    batch_size: 12
    level: 0
    train_patches: 1000
    valid_patches: 250
    tumortypes: human breast cancer,canine lung cancer,canine lymphoma,canine cutaneous
      mast cell tumor,human neuroendocrine tumor,canine soft tissue sarcoma,human
      melanoma
retinanet:
  desc: null
  value:
    scales: 0.2,0.4,0.6,0.8,1.0
    ratios: 1
    sizes: 32
training:
  desc: null
  value:
    lr: 5.0e-05
    num_epochs: 100
    checkpoint: all
x-validation:
  desc: null
  value:
    train: '["001.tiff", "002.tiff", "003.tiff", "004.tiff", "005.tiff", "008.tiff",
      "009.tiff", "010.tiff", "011.tiff", "013.tiff", "017.tiff", "020.tiff", "021.tiff",
      "022.tiff", "023.tiff", "024.tiff", "025.tiff", "027.tiff", "028.tiff", "033.tiff",
      "034.tiff", "036.tiff", "037.tiff", "038.tiff", "040.tiff", "041.tiff", "042.tiff",
      "043.tiff", "044.tiff", "045.tiff", "046.tiff", "047.tiff", "048.tiff", "049.tiff",
      "051.tiff", "053.tiff", "054.tiff", "055.tiff", "056.tiff", "060.tiff", "061.tiff",
      "062.tiff", "065.tiff", "067.tiff", "069.tiff", "070.tiff", "072.tiff", "073.tiff",
      "075.tiff", "076.tiff", "077.tiff", "078.tiff", "079.tiff", "081.tiff", "082.tiff",
      "083.tiff", "084.tiff", "085.tiff", "086.tiff", "087.tiff", "089.tiff", "090.tiff",
      "096.tiff", "097.tiff", "098.tiff", "099.tiff", "101.tiff", "103.tiff", "105.tiff",
      "106.tiff", "108.tiff", "110.tiff", "111.tiff", "112.tiff", "113.tiff", "114.tiff",
      "117.tiff", "118.tiff", "119.tiff", "120.tiff", "121.tiff", "122.tiff", "125.tiff",
      "126.tiff", "130.tiff", "131.tiff", "132.tiff", "133.tiff", "135.tiff", "136.tiff",
      "137.tiff", "138.tiff", "139.tiff", "140.tiff", "141.tiff", "142.tiff", "143.tiff",
      "144.tiff", "145.tiff", "146.tiff", "148.tiff", "149.tiff", "202.tiff", "204.tiff",
      "205.tiff", "207.tiff", "208.tiff", "210.tiff", "213.tiff", "214.tiff", "215.tiff",
      "216.tiff", "217.tiff", "219.tiff", "221.tiff", "222.tiff", "223.tiff", "225.tiff",
      "228.tiff", "231.tiff", "233.tiff", "235.tiff", "237.tiff", "238.tiff", "240.tiff",
      "242.tiff", "243.tiff", "244.tiff", "245.tiff", "247.tiff", "248.tiff", "250.tiff",
      "254.tiff", "258.tiff", "259.tiff", "260.tiff", "261.tiff", "263.tiff", "264.tiff",
      "266.tiff", "267.tiff", "270.tiff", "272.tiff", "273.tiff", "274.tiff", "275.tiff",
      "277.tiff", "278.tiff", "279.tiff", "280.tiff", "281.tiff", "282.tiff", "283.tiff",
      "284.tiff", "285.tiff", "286.tiff", "287.tiff", "288.tiff", "289.tiff", "290.tiff",
      "293.tiff", "294.tiff", "296.tiff", "297.tiff", "298.tiff", "299.tiff", "302.tiff",
      "303.tiff", "304.tiff", "306.tiff", "307.tiff", "309.tiff", "312.tiff", "313.tiff",
      "314.tiff", "316.tiff", "317.tiff", "318.tiff", "319.tiff", "320.tiff", "322.tiff",
      "324.tiff", "325.tiff", "326.tiff", "327.tiff", "331.tiff", "332.tiff", "333.tiff",
      "337.tiff", "340.tiff", "341.tiff", "343.tiff", "347.tiff", "348.tiff", "349.tiff",
      "351.tiff", "352.tiff", "355.tiff", "357.tiff", "358.tiff", "360.tiff", "361.tiff",
      "363.tiff", "364.tiff", "365.tiff", "367.tiff", "369.tiff", "371.tiff", "372.tiff",
      "374.tiff", "378.tiff", "379.tiff", "381.tiff", "382.tiff", "384.tiff", "385.tiff",
      "388.tiff", "393.tiff", "394.tiff", "397.tiff", "399.tiff", "400.tiff", "401.tiff",
      "402.tiff", "403.tiff", "405.tiff", "406.tiff", "407.tiff", "409.tiff", "410.tiff",
      "411.tiff", "412.tiff", "415.tiff", "416.tiff", "417.tiff", "418.tiff", "421.tiff",
      "423.tiff", "424.tiff", "428.tiff", "430.tiff", "432.tiff", "433.tiff", "434.tiff",
      "435.tiff", "436.tiff", "437.tiff", "438.tiff", "440.tiff", "443.tiff", "444.tiff",
      "445.tiff", "446.tiff", "447.tiff", "448.tiff", "449.tiff", "450.tiff", "452.tiff",
      "453.tiff", "454.tiff", "457.tiff", "459.tiff", "461.tiff", "464.tiff", "467.tiff",
      "469.tiff", "470.tiff", "473.tiff", "474.tiff", "478.tiff", "479.tiff", "480.tiff",
      "483.tiff", "486.tiff", "488.tiff", "489.tiff", "490.tiff", "492.tiff", "493.tiff",
      "494.tiff", "498.tiff", "500.tiff", "501.tiff", "503.tiff", "506.tiff", "507.tiff",
      "508.tiff", "509.tiff", "511.tiff", "514.tiff", "516.tiff", "517.tiff", "518.tiff",
      "520.tiff", "521.tiff", "523.tiff", "524.tiff", "525.tiff", "526.tiff", "527.tiff",
      "529.tiff", "530.tiff", "532.tiff", "535.tiff", "536.tiff", "540.tiff", "542.tiff",
      "543.tiff", "544.tiff", "545.tiff", "547.tiff", "548.tiff", "551.tiff", "553.tiff"]'
    valid: '["012.tiff", "016.tiff", "019.tiff", "030.tiff", "039.tiff", "063.tiff",
      "068.tiff", "071.tiff", "080.tiff", "091.tiff", "092.tiff", "094.tiff", "127.tiff",
      "129.tiff", "134.tiff", "201.tiff", "206.tiff", "209.tiff", "211.tiff", "224.tiff",
      "226.tiff", "227.tiff", "229.tiff", "246.tiff", "255.tiff", "262.tiff", "265.tiff",
      "271.tiff", "300.tiff", "301.tiff", "308.tiff", "321.tiff", "323.tiff", "328.tiff",
      "330.tiff", "334.tiff", "335.tiff", "342.tiff", "350.tiff", "356.tiff", "359.tiff",
      "362.tiff", "376.tiff", "377.tiff", "380.tiff", "387.tiff", "391.tiff", "392.tiff",
      "395.tiff", "396.tiff", "404.tiff", "408.tiff", "420.tiff", "429.tiff", "431.tiff",
      "441.tiff", "451.tiff", "455.tiff", "460.tiff", "462.tiff", "465.tiff", "466.tiff",
      "468.tiff", "471.tiff", "475.tiff", "482.tiff", "495.tiff", "496.tiff", "499.tiff",
      "502.tiff", "505.tiff", "513.tiff", "515.tiff", "519.tiff", "522.tiff", "546.tiff",
      "549.tiff", "550.tiff"]'
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.4
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711586062.0
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 50
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 41
      - 50
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.11
      5: 0.16.4
      8:
      - 3
      - 5
      13: windows-amd64
